language: node_js
install:
- npm install codecov -g
- npm ci
script:
- npm test
- codecov
node_js:
- 10
- lts/*
notifications:
  slack:
    if: type = pull_request
    secure: VJFXfBzVVfxAxhUzAIXmqicFc5V/5dUU1E/SvNUiw2COxgqrt+JR0Ds22UnlhynL15h/6yIObVnI1BsdXifhJZvC896MII6MZyHXM19NPgWhWgtUL5HHyrL6hPmrDeIlSOkqcCViXW0DWdjIfzx+yCfbtAOQ1B+SJ7wy1HYFFg5ZsrFdzv9+/VV6Mw3wTbRzsUNtlhtpTeKh7yjIrj1WOSBbq/Taca9XzsrBCjJRrJ7ADCyIiHs9Ixw5A1r1g5pYEOLx82wQZ15AE9HQ9P6Uwep/Bfls1Pp5jgIQIjiDx3aTQT2ANX37jPvkLqm6a0LHO4U03qChsr5T/uCtc7daMzo5tgULtdIWKlvLB8rS2KqZIq661GW0Yps4ovivxStuIJMs3Nw3hxtX5KtsqZ4JS1hDSKSp2nKsoDPRPpA50zg++dDUmsGSyNwYP1JKtnBH8VyP0PvKGevTE8820D0hbBhPcu20d1+BYcYFUFAcZHybmkFF46nQcklhohiA1paQquJNkf2AOpbSxQIII7N9xo+WOqEU2T8wHlqC3RK26y+0Oj+zGuK8HIYTU14BTSkXIeCvZWnrmT2HwdtNqrIFOgJKa5IgsSVpDGSa27AIRXkEL8HZn1JtTV00aKtFLOiRbWM0PP2D6xgqU5bHVD96lFbKu5t5MOwhraSqsr5I7QM=
